////
// tinkers construct
//// renik

//
ServerEvents.recipes(event => {
//

  //REMOVE
  event.remove({id: 'tconstruct:small_axe_head_sand_cast'})
  event.remove({id: 'tconstruct:broad_axe_head_red_sand_cast'})
  event.remove({id: 'tconstruct:wire_sand_cast'})
  event.remove({id: 'tconstruct:rod_red_sand_cast'})
  event.remove({id: 'tconstruct:rod_sand_cast'})
  event.remove({id: 'tconstruct:bow_grip_red_sand_cast'})
  event.remove({id: 'tconstruct:round_plate_red_sand_cast'})
  event.remove({id: 'tconstruct:small_axe_head_red_sand_cast'})
  event.remove({id: 'tconstruct:broad_blade_red_sand_cast'})
  event.remove({id: 'tconstruct:large_plate_red_sand_cast'})
  event.remove({id: 'tconstruct:gem_red_sand_cast'})
  event.remove({id: 'tconstruct:coin_red_sand_cast'})
  event.remove({id: 'tconstruct:tool_handle_sand_cast'})
  event.remove({id: 'tconstruct:blank_sand_cast'})
  event.remove({id: 'tconstruct:repair_kit_red_sand_cast'})
  event.remove({id: 'tconstruct:nugget_red_sand_cast'})
  event.remove({id: 'tconstruct:tool_binding_sand_cast'})
  event.remove({id: 'tconstruct:plate_red_sand_cast'})
  event.remove({id: 'tconstruct:bow_grip_sand_cast'})
  event.remove({id: 'tconstruct:tough_handle_sand_cast'})
  event.remove({id: 'tconstruct:hammer_head_sand_cast'})
  event.remove({id: 'tconstruct:round_plate_sand_cast'})
  event.remove({id: 'tconstruct:coin_sand_cast'})
  event.remove({id: 'tconstruct:pick_head_red_sand_cast'})
  event.remove({id: 'tconstruct:blank_red_sand_cast'})
  event.remove({id: 'tconstruct:tool_handle_red_sand_cast'})
  event.remove({id: 'tconstruct:gear_sand_cast'})
  event.remove({id: 'tconstruct:pick_head_sand_cast'})
  event.remove({id: 'tconstruct:bow_limb_sand_cast'})
  event.remove({id: 'tconstruct:bow_limb_red_sand_cast'})
  event.remove({id: 'tconstruct:repair_kit_sand_cast'})
  event.remove({id: 'tconstruct:broad_blade_sand_cast'})
  event.remove({id: 'tconstruct:broad_axe_head_sand_cast'})
  event.remove({id: 'tconstruct:hammer_head_red_sand_cast'})
  event.remove({id: 'tconstruct:tool_binding_red_sand_cast'})
  event.remove({id: 'tconstruct:tough_handle_red_sand_cast'})
  event.remove({id: 'tconstruct:small_blade_red_sand_cast'})
  event.remove({id: 'tconstruct:gem_sand_cast'})
  event.remove({id: 'tconstruct:nugget_sand_cast'})
  event.remove({id: 'tconstruct:gear_red_sand_cast'})
  event.remove({id: 'tconstruct:plate_sand_cast'})
  event.remove({id: 'tconstruct:large_plate_sand_cast'})
  event.remove({id: 'tconstruct:wire_red_sand_cast'})
  event.remove({id: 'tconstruct:small_blade_sand_cast'})
  event.remove({id: 'tconstruct:nugget_cast'})
	event.remove({id: 'tconstruct:small_blade_cast'})
	event.remove({id: 'tconstruct:gem_cast'})
	event.remove({id: 'tconstruct:tool_handle_cast'})
	event.remove({id: 'tconstruct:plate_cast'})
	event.remove({id: 'tconstruct:repair_kit_cast'})
	event.remove({id: 'tconstruct:gear_cast'})
	event.remove({id: 'tconstruct:broad_blade_cast'})
	event.remove({id: 'tconstruct:wire_cast'})
	event.remove({id: 'tconstruct:tough_handle_cast'})
	event.remove({id: 'tconstruct:bow_limb_cast'})
	event.remove({id: 'tconstruct:round_plate_cast'})
	event.remove({id: 'tconstruct:rod_cast'})
	event.remove({id: 'tconstruct:large_plate_cast'})
	event.remove({id: 'tconstruct:hammer_head_cast'})
	event.remove({id: 'tconstruct:pick_head_cast'})
	event.remove({id: 'tconstruct:bow_grip_cast'})
	event.remove({id: 'tconstruct:coin_cast'})
	event.remove({id: 'tconstruct:tool_binding_cast'})
	event.remove({id: 'tconstruct:broad_axe_head_cast'})
	event.remove({id: 'tconstruct:small_axe_head_cast'})	

//
})
//