////
// tinkers construct
//// renik

//
ServerEvents.recipes(event => {
//

  //REMOVE
  // event.remove({id: 'tconstruct:small_axe_head_sand_cast'})
  // event.remove({id: 'tconstruct:broad_axe_head_red_sand_cast'})
  // event.remove({id: 'tconstruct:wire_sand_cast'})
  // event.remove({id: 'tconstruct:rod_red_sand_cast'})
  // event.remove({id: 'tconstruct:rod_sand_cast'})
  // event.remove({id: 'tconstruct:bow_grip_red_sand_cast'})
  // event.remove({id: 'tconstruct:round_plate_red_sand_cast'})
  // event.remove({id: 'tconstruct:small_axe_head_red_sand_cast'})
  // event.remove({id: 'tconstruct:broad_blade_red_sand_cast'})
  // event.remove({id: 'tconstruct:large_plate_red_sand_cast'})
  // event.remove({id: 'tconstruct:gem_red_sand_cast'})
  // event.remove({id: 'tconstruct:coin_red_sand_cast'})
  // event.remove({id: 'tconstruct:tool_handle_sand_cast'})
  // event.remove({id: 'tconstruct:blank_sand_cast'})
  // event.remove({id: 'tconstruct:repair_kit_red_sand_cast'})
  // event.remove({id: 'tconstruct:nugget_red_sand_cast'})
  // event.remove({id: 'tconstruct:tool_binding_sand_cast'})
  // event.remove({id: 'tconstruct:plate_red_sand_cast'})
  // event.remove({id: 'tconstruct:bow_grip_sand_cast'})
  // event.remove({id: 'tconstruct:tough_handle_sand_cast'})
  // event.remove({id: 'tconstruct:hammer_head_sand_cast'})
  // event.remove({id: 'tconstruct:round_plate_sand_cast'})
  // event.remove({id: 'tconstruct:coin_sand_cast'})
  // event.remove({id: 'tconstruct:pick_head_red_sand_cast'})
  // event.remove({id: 'tconstruct:blank_red_sand_cast'})
  // event.remove({id: 'tconstruct:tool_handle_red_sand_cast'})
  // event.remove({id: 'tconstruct:gear_sand_cast'})
  // event.remove({id: 'tconstruct:pick_head_sand_cast'})
  // event.remove({id: 'tconstruct:bow_limb_sand_cast'})
  // event.remove({id: 'tconstruct:bow_limb_red_sand_cast'})
  // event.remove({id: 'tconstruct:repair_kit_sand_cast'})
  // event.remove({id: 'tconstruct:broad_blade_sand_cast'})
  // event.remove({id: 'tconstruct:broad_axe_head_sand_cast'})
  // event.remove({id: 'tconstruct:hammer_head_red_sand_cast'})
  // event.remove({id: 'tconstruct:tool_binding_red_sand_cast'})
  // event.remove({id: 'tconstruct:tough_handle_red_sand_cast'})
  // event.remove({id: 'tconstruct:small_blade_red_sand_cast'})
  // event.remove({id: 'tconstruct:gem_sand_cast'})
  // event.remove({id: 'tconstruct:nugget_sand_cast'})
  // event.remove({id: 'tconstruct:gear_red_sand_cast'})
  // event.remove({id: 'tconstruct:plate_sand_cast'})
  // event.remove({id: 'tconstruct:large_plate_sand_cast'})
  // event.remove({id: 'tconstruct:wire_red_sand_cast'})
  // event.remove({id: 'tconstruct:small_blade_sand_cast'})

  // event.remove({id: 'tconstruct:smeltery/casts/gold/helmet_plating_sand'})
  // event.remove({id: 'tconstruct:smeltery/casts/gold/chestplate_plating_sand'})
  // event.remove({id: 'tconstruct:smeltery/casts/gold/leggings_plating_sand'})
  // event.remove({id: 'tconstruct:smeltery/casts/gold/maille_sand'})

  // event.remove({id: 'tconstruct:smeltery/casts/gold/helmet_plating_red_sand'})
  // event.remove({id: 'tconstruct:smeltery/casts/gold/chestplate_plating_red_sand'})
  // event.remove({id: 'tconstruct:smeltery/casts/gold/leggings_plating_red_sand'})
  // event.remove({id: 'tconstruct:maille_red_sand'})

event.remove({id: 'tconstruct:smeltery/casts/gold/small_blade'})
event.remove({id: 'tconstruct:smeltery/casts/gold/gems'})
event.remove({id: 'tconstruct:smeltery/casts/gold/tool_handle'})
event.remove({id: 'tconstruct:smeltery/casts/gold/plates'})
event.remove({id: 'tconstruct:smeltery/casts/gold/repair_kit'})
event.remove({id: 'tconstruct:smeltery/casts/gold/gears'})
event.remove({id: 'tconstruct:smeltery/casts/gold/broad_blade'})
event.remove({id: 'tconstruct:smeltery/casts/gold/wires'})
event.remove({id: 'tconstruct:smeltery/casts/gold/tough_handle'})
event.remove({id: 'tconstruct:smeltery/casts/gold/bow_limb'})
event.remove({id: 'tconstruct:smeltery/casts/gold/round_plate'})
event.remove({id: 'tconstruct:smeltery/casts/gold/rods'})
event.remove({id: 'tconstruct:smeltery/casts/gold/large_plate'})
event.remove({id: 'tconstruct:smeltery/casts/gold/hammer_head'})
event.remove({id: 'tconstruct:smeltery/casts/gold/pick_head'})
event.remove({id: 'tconstruct:smeltery/casts/gold/bow_grip'})
event.remove({id: 'tconstruct:smeltery/casts/gold/coins'})
event.remove({id: 'tconstruct:smeltery/casts/gold/tool_binding'})
event.remove({id: 'tconstruct:smeltery/casts/gold/helmet_plating'})
event.remove({id: 'tconstruct:smeltery/casts/gold/chestplate_plating'})
event.remove({id: 'tconstruct:smeltery/casts/gold/leggings_plating'})
event.remove({id: 'tconstruct:smeltery/casts/gold/boots_plating'})
event.remove({id: 'tconstruct:smeltery/casts/gold/maille'})
event.remove({id: 'tconstruct:smeltery/casts/gold/broad_axe_head'})
event.remove({id: 'tconstruct:smeltery/casts/gold/small_axe_head'})

event.remove({id: 'tconstruct:smeltery/casts/sand/molding/small_blade'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/gems'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/tool_handle'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/plates'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/repair_kit'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/gears'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/broad_blade'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/wires'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/tough_handle'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/bow_limb'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/round_plate'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/rods'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/large_plate'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/hammer_head'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/pick_head'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/bow_grip'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/coins'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/tool_binding'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/helmet_plating'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/chestplate_plating'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/leggings_plating'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/boots_plating'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/maille'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/broad_axe_head'})
event.remove({id: 'tconstruct:smeltery/casts/sand/molding/small_axe_head'})

event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/small_blade'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/gems'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/tool_handle'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/plates'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/repair_kit'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/gears'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/broad_blade'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/wires'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/tough_handle'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/bow_limb'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/round_plate'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/rods'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/large_plate'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/hammer_head'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/pick_head'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/bow_grip'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/coins'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/tool_binding'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/helmet_plating'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/chestplate_plating'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/leggings_plating'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/boots_plating'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/maille'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/broad_axe_head'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/molding/small_axe_head'})

event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/small_blade'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/gems'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/tool_handle'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/plates'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/repair_kit'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/gears'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/broad_blade'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/wires'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/tough_handle'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/bow_limb'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/round_plate'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/rods'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/large_plate'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/hammer_head'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/pick_head'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/bow_grip'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/coins'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/tool_binding'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/helmet_plating'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/chestplate_plating'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/leggings_plating'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/boots_plating'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/maille'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/broad_axe_head'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_block/small_axe_head'})

event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/small_blade'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/gems'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/tool_handle'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/plates'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/repair_kit'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/gears'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/broad_blade'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/wires'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/tough_handle'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/bow_limb'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/round_plate'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/rods'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/large_plate'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/hammer_head'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/pick_head'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/bow_grip'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/coins'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/tool_binding'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/helmet_plating'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/chestplate_plating'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/leggings_plating'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/boots_plating'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/maille'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/broad_axe_head'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_block/small_axe_head'})

event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/small_blade'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/gems'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/tool_handle'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/plates'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/repair_kit'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/gears'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/broad_blade'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/wires'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/tough_handle'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/bow_limb'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/round_plate'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/rods'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/large_plate'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/hammer_head'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/pick_head'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/bow_grip'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/coins'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/tool_binding'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/helmet_plating'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/chestplate_plating'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/leggings_plating'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/boots_plating'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/maille'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/broad_axe_head'})
event.remove({id: 'tconstruct:smeltery/casts/sand/builder_cast/small_axe_head'})

event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/small_blade'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/gems'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/tool_handle'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/plates'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/repair_kit'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/gears'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/broad_blade'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/wires'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/tough_handle'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/bow_limb'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/round_plate'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/rods'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/large_plate'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/hammer_head'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/pick_head'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/bow_grip'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/coins'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/tool_binding'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/helmet_plating'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/chestplate_plating'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/leggings_plating'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/boots_plating'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/maille'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/broad_axe_head'})
event.remove({id: 'tconstruct:smeltery/casts/red_sand/builder_cast/small_axe_head'})



event.remove({id: 'tconstruct:smeltery/casting/scorched/brick_composite'})	
event.remove({id: 'tconstruct:smeltery/seared/grout_multiple'})

//
})
//

//
ServerEvents.recipes(event => {
//

  //ADD

// Grout
  event.shaped('2x tconstruct:grout',
    ['232','414','232'], {
    1: 'minecraft:gravel', 
    2: '#minecraft:sand',
    3: 'minecraft:clay_ball',
    4: 'minecraft:bone_meal'}).id('tconstruct:smeltery/seared/grout')

// Nether Grout
  event.shaped('2x tconstruct:nether_grout',
    ['232','414','232'], {
    1: 'tconstruct:grout', 
    2: 'minecraft:soul_sand',
    3: 'minecraft:magma_cream',
    4: 'minecraft:netherrack'}).id('tconstruct:smeltery/scorched/nether_grout')

// Piggy Backpack
  event.shaped('tconstruct:piggy_backpack',
    ['343','121','333'], {
    1: 'tconstruct:slimesteel_ingot', 
    2: 'industrialforegoing:mob_imprisonment_tool',
    3: '#forge:leather',
    4: 'tconstruct:pig_iron_ingot'}).id('tconstruct:gadgets/piggy_backpack')

//    
})
//