////
// hide stuff from jei / jei cleanup
//// renik

//
JEIEvents.hideItems(event => {
//

// BASALT ORE
	event.hide('emendatusenigmatica:apatite_basalt_ore')
	event.hide('emendatusenigmatica:certus_quartz_basalt_ore')
	event.hide('emendatusenigmatica:charged_certus_quartz_basalt_ore')
	event.hide('emendatusenigmatica:fluix_basalt_ore')
	event.hide('emendatusenigmatica:sharkinite_basalt_ore')
	event.hide('emendatusenigmatica:source_basalt_ore')
	event.hide('emendatusenigmatica:weekonium_basalt_ore')

// BLACKSTONE ORE
	event.hide('emendatusenigmatica:apatite_blackstone_ore')
	event.hide('emendatusenigmatica:charged_certus_quartz_blackstone_ore')
	event.hide('emendatusenigmatica:fluix_blackstone_ore')
	event.hide('emendatusenigmatica:source_blackstone_ore')
	event.hide('emendatusenigmatica:weekonium_blackstone_ore')

// DEEPSLATE ORE
	event.hide('emendatusenigmatica:apatite_deepslate_ore')
	event.hide('emendatusenigmatica:certus_quartz_deepslate_ore')
	event.hide('emendatusenigmatica:charged_certus_quartz_deepslate_ore')
	event.hide('emendatusenigmatica:fluix_deepslate_ore')
	event.hide('emendatusenigmatica:weekonium_deepslate_ore')

// GLACIO STONE ORE
	event.hide('emendatusenigmatica:certus_quartz_glacio_stone_ore')
	event.hide('emendatusenigmatica:charged_certus_quartz_glacio_stone_ore')
	event.hide('emendatusenigmatica:fluix_glacio_stone_ore')
	event.hide('emendatusenigmatica:sharkinite_glacio_stone_ore')
	event.hide('emendatusenigmatica:source_glacio_stone_ore')
	event.hide('emendatusenigmatica:weekonium_glacio_stone_ore')

// STONE ORE
	event.hide('emendatusenigmatica:apatite_stone_ore')
	event.hide('emendatusenigmatica:certus_quartz_stone_ore')
	event.hide('emendatusenigmatica:charged_certus_quartz_stone_ore')
	event.hide('emendatusenigmatica:fluix_stone_ore')
	event.hide('emendatusenigmatica:sharkinite_stone_ore')
	event.hide('emendatusenigmatica:source_stone_ore')

// MARS STONE ORE
	event.hide('emendatusenigmatica:apatite_mars_stone_ore')
	event.hide('emendatusenigmatica:certus_quartz_mars_stone_ore')
	event.hide('emendatusenigmatica:charged_certus_quartz_mars_stone_ore')
	event.hide('emendatusenigmatica:fluix_mars_stone_ore')
	event.hide('emendatusenigmatica:sharkinite_mars_stone_ore')
	event.hide('emendatusenigmatica:source_mars_stone_ore')
	event.hide('emendatusenigmatica:weekonium_mars_stone_ore')

// MERCURY STONE ORE
	event.hide('emendatusenigmatica:apatite_mercury_stone_ore')
	event.hide('emendatusenigmatica:certus_quartz_mercury_stone_ore')
	event.hide('emendatusenigmatica:sharkinite_mercury_stone_ore')
	event.hide('emendatusenigmatica:source_mercury_stone_ore')
	event.hide('emendatusenigmatica:weekonium_mercury_stone_ore')

// MOONSTONE ORE
	event.hide('emendatusenigmatica:certus_quartz_moon_stone_ore')
	event.hide('emendatusenigmatica:charged_certus_quartz_moon_stone_ore')
	event.hide('emendatusenigmatica:fluix_moon_stone_ore')
	event.hide('emendatusenigmatica:sharkinite_moon_stone_ore')
	event.hide('emendatusenigmatica:source_moon_stone_ore')
	event.hide('emendatusenigmatica:weekonium_moon_stone_ore')

// AD ASTRA
	event.hide('ad_astra:steel_engine')
	event.hide('ad_astra:desh_fluid_pipe')
	event.hide('ad_astra:ostrum_fluid_pipe')
	event.hide('ad_astra:cable_duct')
	event.hide('ad_astra:steel_cable')
	event.hide('ad_astra:desh_cable')
	event.hide('ad_astra:fluid_pipe_duct')
	event.hide('ad_astra:energizer')
	event.hide('ad_astra:compressor')
	event.hide('ad_astra:coal_generator')
	event.hide('ad_astra:tier_1_rover')

// STORAGE
	event.hide('ad_astra:aeronos_chest')
	event.hide('ad_astra:strophar_chest')
	event.hide('twilightforest:twilight_oak_chest')
	event.hide('twilightforest:canopy_chest')
	event.hide('twilightforest:mangrove_chest')
	event.hide('twilightforest:darkwood_chest')
	event.hide('twilightforest:time_chest')
	event.hide('twilightforest:transformation_chest')
	event.hide('twilightforest:mining_chest')
	event.hide('twilightforest:sorting_chest')
	event.hide('#cfm:storage')


// SILENT
	event.hide('silentgear:salvager')

// TWILIGHT FOREST
	event.hide('twilightforest:uncrafting_table')

// CREATE
	event.hide('create:windmill_bearing')
	event.hide('create:sail_frame')
	event.hide('create:white_sail')

// METAL BARRELS
	event.hide('metalbarrels:silver_to_diamond')
	event.hide('metalbarrels:silver_to_netherite')
	event.hide('metalbarrels:wood_to_netherite')
	event.hide('metalbarrels:wood_to_diamond')
	event.hide('metalbarrels:wood_to_obsidian')
	event.hide('metalbarrels:iron_to_gold')
	event.hide('metalbarrels:copper_to_obsidian')
	event.hide('metalbarrels:copper_to_silver')
	event.hide('metalbarrels:iron_to_diamond')
	event.hide('metalbarrels:silver_to_obsidian')
	event.hide('metalbarrels:copper_to_netherite')
	event.hide('metalbarrels:gold_to_obsidian')
	event.hide('metalbarrels:wood_to_gold')
	event.hide('metalbarrels:gold_to_netherite')
	event.hide('metalbarrels:iron_to_obsidian')
	event.hide('metalbarrels:wood_to_silver')
	event.hide('metalbarrels:iron_to_netherite')
	event.hide('metalbarrels:wood_to_iron')
	event.hide('metalbarrels:copper_to_gold')
	event.hide('metalbarrels:copper_to_diamond')
	event.hide('metalbarrels:diamond_to_netherite')
	event.hide('metalbarrels:wood_to_crystal')
	event.hide('metalbarrels:copper_to_crystal')
	event.hide('metalbarrels:iron_to_crystal')
	event.hide('metalbarrels:silver_to_crystal')
	event.hide('metalbarrels:gold_to_crystal')
	event.hide('metalbarrels:diamond_to_crystal')
	event.hide('metalbarrels:crystal_barrel')

// BOTANY POTS
	event.hide('botanypots:light_blue_concrete_botany_pot')
	event.hide('botanypots:purple_concrete_hopper_botany_pot')
	event.hide('botanypots:orange_terracotta_hopper_botany_pot')
	event.hide('botanypots:brown_concrete_hopper_botany_pot')
	event.hide('botanypots:lime_concrete_botany_pot')
	event.hide('botanypots:purple_glazed_terracotta_botany_pot')
	event.hide('botanypots:yellow_glazed_terracotta_botany_pot')
	event.hide('botanypots:brown_glazed_terracotta_botany_pot')
	event.hide('botanypots:red_terracotta_botany_pot')
	event.hide('botanypots:red_terracotta_botany_pot')
	event.hide('botanypots:brown_glazed_terracotta_hopper_botany_pot')
	event.hide('botanypots:gray_glazed_terracotta_hopper_botany_pot')
	event.hide('botanypots:blue_terracotta_botany_pot')
	event.hide('botanypots:light_gray_terracotta_botany_pot')
	event.hide('botanypots:red_terracotta_hopper_botany_pot')
	event.hide('botanypots:yellow_concrete_hopper_botany_pot')
	event.hide('botanypots:blue_terracotta_hopper_botany_pot')
	event.hide('botanypots:green_terracotta_botany_pot')
	event.hide('botanypots:yellow_terracotta_botany_pot')
	event.hide('botanypots:gray_glazed_terracotta_botany_pot')
	event.hide('botanypots:black_concrete_hopper_botany_pot')
	event.hide('botanypots:pink_concrete_botany_pot')
	event.hide('botanypots:light_blue_glazed_terracotta_hopper_botany_pot')
	event.hide('botanypots:blue_glazed_terracotta_botany_pot')
	event.hide('botanypots:orange_concrete_botany_pot')
	event.hide('botanypots:orange_glazed_terracotta_hopper_botany_pot')
	event.hide('botanypots:gray_terracotta_botany_pot')
	event.hide('botanypots:white_terracotta_hopper_botany_pot')
	event.hide('botanypots:cyan_concrete_hopper_botany_pot')
	event.hide('botanypots:magenta_concrete_botany_pot')
	event.hide('botanypots:red_glazed_terracotta_hopper_botany_pot')
	event.hide('botanypots:red_concrete_botany_pot')
	event.hide('botanypots:light_gray_terracotta_hopper_botany_pot')
	event.hide('botanypots:orange_concrete_hopper_botany_pot')
	event.hide('botanypots:blue_concrete_hopper_botany_pot')
	event.hide('botanypots:purple_glazed_terracotta_hopper_botany_pot')
	event.hide('botanypots:white_concrete_hopper_botany_pot')
	event.hide('botanypots:gray_concrete_botany_pot')
	event.hide('botanypots:white_glazed_terracotta_hopper_botany_pot')
	event.hide('botanypots:green_concrete_botany_pot')
	event.hide('botanypots:lime_terracotta_botany_pot')
	event.hide('botanypots:pink_concrete_hopper_botany_pot')
	event.hide('botanypots:magenta_terracotta_hopper_botany_pot')
	event.hide('botanypots:lime_glazed_terracotta_botany_pot')
	event.hide('botanypots:black_terracotta_hopper_botany_pot')
	event.hide('botanypots:magenta_concrete_hopper_botany_pot')
	event.hide('botanypots:light_blue_terracotta_hopper_botany_pot')
	event.hide('botanypots:pink_glazed_terracotta_botany_pot')
	event.hide('botanypots:blue_glazed_terracotta_hopper_botany_pot')
	event.hide('botanypots:light_gray_concrete_hopper_botany_pot')
	event.hide('botanypots:magenta_glazed_terracotta_hopper_botany_pot')
	event.hide('botanypots:pink_terracotta_botany_pot')
	event.hide('botanypots:brown_concrete_botany_pot')
	event.hide('botanypots:cyan_glazed_terracotta_botany_pot')
	event.hide('botanypots:light_gray_concrete_botany_pot')
	event.hide('botanypots:pink_glazed_terracotta_hopper_botany_pot')
	event.hide('botanypots:gray_terracotta_hopper_botany_pot')
	event.hide('botanypots:brown_terracotta_botany_pot')
	event.hide('botanypots:green_glazed_terracotta_hopper_botany_pot')
	event.hide('botanypots:green_concrete_hopper_botany_pot')
	event.hide('botanypots:white_terracotta_botany_pot')
	event.hide('botanypots:orange_terracotta_botany_pot')
	event.hide('botanypots:brown_terracotta_hopper_botany_pot')
	event.hide('botanypots:lime_glazed_terracotta_hopper_botany_pot')
	event.hide('botanypots:red_glazed_terracotta_botany_pot')
	event.hide('botanypots:green_terracotta_hopper_botany_pot')
	event.hide('botanypots:green_glazed_terracotta_botany_pot')
	event.hide('botanypots:lime_concrete_hopper_botany_pot')
	event.hide('botanypots:orange_glazed_terracotta_botany_pot')
	event.hide('botanypots:blue_concrete_botany_pot')
	event.hide('botanypots:light_gray_glazed_terracotta_hopper_botany_pot')
	event.hide('botanypots:black_glazed_terracotta_hopper_botany_pot')
	event.hide('botanypots:yellow_glazed_terracotta_hopper_botany_pot')
	event.hide('botanypots:gray_concrete_hopper_botany_pot')
	event.hide('botanypots:cyan_terracotta_hopper_botany_pot')
	event.hide('botanypots:black_terracotta_botany_pot')
	event.hide('botanypots:white_concrete_botany_pot')
	event.hide('botanypots:purple_terracotta_hopper_botany_pot')
	event.hide('botanypots:cyan_terracotta_botany_pot')
	event.hide('botanypots:magenta_terracotta_botany_pot')
	event.hide('botanypots:light_gray_glazed_terracotta_botany_pot')
	event.hide('botanypots:purple_terracotta_botany_pot')
	event.hide('botanypots:cyan_glazed_terracotta_hopper_botany_pot')
	event.hide('botanypots:light_blue_terracotta_botany_pot')
	event.hide('botanypots:pink_terracotta_hopper_botany_pot')
	event.hide('botanypots:magenta_glazed_terracotta_botany_pot')
	event.hide('botanypots:light_blue_concrete_hopper_botany_pot')
	event.hide('botanypots:yellow_concrete_botany_pot')
	event.hide('botanypots:black_glazed_terracotta_botany_pot')
	event.hide('botanypots:light_blue_glazed_terracotta_botany_pot')
	event.hide('botanypots:yellow_terracotta_hopper_botany_pot')
	event.hide('botanypots:red_concrete_hopper_botany_pot')
	event.hide('botanypots:black_concrete_botany_pot')
	event.hide('botanypots:lime_terracotta_hopper_botany_pot')
	event.hide('botanypots:cyan_concrete_botany_pot')
	event.hide('botanypots:purple_concrete_botany_pot')
	event.hide('botanypots:white_glazed_terracotta_botany_pot')

// BOTANIA
	event.hide('botania:apothecary_forest')
	event.hide('botania:apothecary_plains')
	event.hide('botania:apothecary_mountain')
	event.hide('botania:apothecary_fungal')
	event.hide('botania:apothecary_swamp')
	event.hide('botania:apothecary_desert')
	event.hide('botania:apothecary_taiga')
	event.hide('botania:apothecary_mesa')
	event.hide('botania:apothecary_mossy')
	event.hide('botania:apothecary_deepslate')
	event.hide('botania:pixie_dust')

// OCCULTISM
	event.hide('theurgy:divination_rod_t4')

// SIMPLE STORAGE
	event.hide('storagenetwork:inventory')
	event.hide('storagenetwork:exchange')
	event.hide('storagenetwork:collector')
	event.hide('storagenetwork:stock_upgrade')
	event.hide('storagenetwork:operation_upgrade')
	event.hide('storagenetwork:crafting_remote')
	event.hide('storagenetwork:picker_remote')
	event.hide('storagenetwork:collector_remote')
	event.hide('storagenetwork:builder_remote')

// SOPHISTICATED BACKPACKS
	event.hide('sophisticatedbackpacks:compacting_upgrade')
	event.hide('sophisticatedbackpacks:advanced_compacting_upgrade')
	event.hide('sophisticatedbackpacks:battery_upgrade')
	event.hide('sophisticatedbackpacks:inception_upgrade')
	event.hide('sophisticatedbackpacks:smelting_upgrade')
	event.hide('sophisticatedbackpacks:auto_smelting_upgrade')
	event.hide('sophisticatedbackpacks:smoking_upgrade')
	event.hide('sophisticatedbackpacks:auto_smoking_upgrade')
	event.hide('sophisticatedbackpacks:blasting_upgrade')
	event.hide('sophisticatedbackpacks:auto_blasting_upgrade')
	event.hide('sophisticatedbackpacks:pump_upgrade')
	event.hide('sophisticatedbackpacks:advanced_pump_upgrade')


// THERMAL
	event.hide('thermal:dynamo_lapidary')
	event.hide('thermal:dynamo_magmatic')
	event.hide('thermal:dynamo_numismatic')
	event.hide('thermal:dynamo_disenchantment')
	event.hide('thermal:machine_frame')
	event.hide('thermal:ender_pearl_dust')
	event.hide('thermal:creosote')
	event.hide('thermal:creosote_bucket')
	event.hide('thermal:creosote')
	event.hide('thermal:netherite_gear')
	event.hide('thermal:emerald_gear')
	event.hide('thermal:quartz_gear')
	event.hide('thermal:fluid_placer')

// RF TOOLS
	event.hide('rftoolsbase:machine_frame')
	event.hide('rftoolsutility:flight_module')

// MEKANISM
	event.hide('mekanism:dust_quartz')
	

// FARMERS DELIGHT
	event.hide('#farmersdelight:cabinets')
	event.hide('farmersdelight:wheat_dough')

// INDUSTRIAL FOREGOING
	event.hide('industrialforegoing:mob_slaughter_factory')
	event.hide('industrialforegoing:mob_crusher')
	event.hide('industrialforegoing:mob_duplicator')
	event.hide('industrialforegoing:mob_detector')
	event.hide('industrialforegoing:conveyor')
	event.hide('industrialforegoing:conveyor_extraction_upgrade')
	event.hide('industrialforegoing:conveyor_insertion_upgrade')
	event.hide('industrialforegoing:conveyor_detection_upgrade')
	event.hide('industrialforegoing:conveyor_bouncing_upgrade')
	event.hide('industrialforegoing:conveyor_dropping_upgrade')
	event.hide('industrialforegoing:conveyor_blinking_upgrade')
	event.hide('industrialforegoing:conveyor_splitting_upgrade')
	event.hide('industrialforegoing:sewage_composter')
	event.hide('industrialforegoing:fertilizer')
	event.hide('industrialforegoing:fluid_placer')

// BLOCKHEADS
	event.hide('farmingforblockheads:feeding_trough')

// ANGELRING
	event.hide('angelring:energetic_angel_ring')
	event.hide('angelring:leadstone_angel_ring')
	event.hide('angelring:hardened_angel_ring')
	event.hide('angelring:reinforced_angel_ring')

// TEMPAD
	event.hide('tempad:tempad')

// Mystical Agriculture
	event.hide('mysticalagriculture:rubber_seeds')
	event.hide('mysticalagriculture:graphite_seeds')
	event.hide('mysticalagriculture:mithril_seeds')
	event.hide('mysticalagriculture:tungsten_seeds')
	event.hide('mysticalagriculture:ruby_seeds')
	event.hide('mysticalagriculture:chrome_seeds')
	event.hide('mysticalagriculture:titanium_seeds')
	event.hide('mysticalagriculture:sapphire_seeds')
	event.hide('mysticalagriculture:platinum_seeds')
	event.hide('mysticalagriculture:aluminum_seeds')
	event.hide('mysticalagriculture:slime_seeds')
	event.hide('mysticalagriculture:basalz_seeds')
	event.hide('mysticalagriculture:blizz_seeds')
	event.hide('mysticalagriculture:blitz_seeds')
	event.hide('mysticalagriculture:bronze_seeds')
	event.hide('mysticalagriculture:copper_seeds')
	event.hide('mysticalagriculture:nether_quartz_seeds')
	event.hide('mysticalagriculture:lead_seeds')
	event.hide('mysticalagriculture:manasteel_seeds')
	event.hide('mysticalagriculture:prismarine_seeds')
	event.hide('mysticalagriculture:redstone_seeds')
	event.hide('mysticalagriculture:silver_seeds')
	event.hide('mysticalagriculture:skeleton_seeds')
	event.hide('mysticalagriculture:tin_seeds')
	event.hide('mysticalagriculture:zinc_seeds')
	event.hide('mysticalagriculture:zombie_seeds')
	event.hide('mysticalagriculture:chicken_seeds')
	event.hide('mysticalagriculture:cow_seeds')
	event.hide('mysticalagriculture:fish_seeds')
	event.hide('mysticalagriculture:pig_seeds')
	event.hide('mysticalagriculture:sheep_seeds')
	event.hide('mysticalagriculture:squid_seeds')
	event.hide('mysticalagriculture:turtle_seeds')
	event.hide('mysticalagriculture:creeper_seeds')
	event.hide('mysticalagriculture:spider_seeds')
	event.hide('mysticalagriculture:rabbit_seeds')
	event.hide('mysticalagriculture:blaze_seeds')
	event.hide('mysticalagriculture:enderman_seeds')
	event.hide('mysticalagriculture:rubber_essence')
	event.hide('mysticalagriculture:graphite_essence')
	event.hide('mysticalagriculture:mithril_essence')
	event.hide('mysticalagriculture:tungsten_essence')
	event.hide('mysticalagriculture:ruby_essence')
	event.hide('mysticalagriculture:chrome_essence')
	event.hide('mysticalagriculture:titanium_essence')
	event.hide('mysticalagriculture:sapphire_essence')
	event.hide('mysticalagriculture:platinum_essence')
	event.hide('mysticalagriculture:aluminum_essence')
	// event.hide('mysticalagriculture:slime_essence')
	event.hide('mysticalagriculture:basalz_essence')
	event.hide('mysticalagriculture:blizz_essence')
	event.hide('mysticalagriculture:blitz_essence')
	event.hide('mysticalagriculture:bronze_essence')
	// event.hide('mysticalagriculture:copper_essence')
	event.hide('mysticalagriculture:nether_quartz_essence')
	event.hide('mysticalagriculture:lead_essence')
	event.hide('mysticalagriculture:manasteel_essence')
	event.hide('mysticalagriculture:prismarine_essence')
	event.hide('mysticalagriculture:redstone_essence')
	event.hide('mysticalagriculture:silver_essence')
	event.hide('mysticalagriculture:skeleton_essence')
	event.hide('mysticalagriculture:tin_essence')
	// event.hide('mysticalagriculture:zinc_essence')
	// event.hide('mysticalagriculture:zombie_essence')
	event.hide('mysticalagriculture:chicken_essence')
	// event.hide('mysticalagriculture:cow_essence')
	event.hide('mysticalagriculture:fish_essence')
	// event.hide('mysticalagriculture:pig_essence')
	// event.hide('mysticalagriculture:sheep_essence')
	event.hide('mysticalagriculture:squid_essence')
	event.hide('mysticalagriculture:turtle_essence')
	event.hide('mysticalagriculture:creeper_essence')
	event.hide('mysticalagriculture:spider_essence')
	event.hide('mysticalagriculture:rabbit_essence')
	// event.hide('mysticalagriculture:blaze_essence')
	event.hide('mysticalagriculture:enderman_essence')
	event.hide('mysticalagriculture:machine_frame')
	event.hide('mysticalagriculture:amethyst_bronze_seeds')
	event.hide('mysticalagriculture:hepatizon_seeds')
	event.hide('mysticalagriculture:rose_gold_seeds')
	event.hide('mysticalagriculture:amethyst_bronze_essence')
	event.hide('mysticalagriculture:hepatizon_essence')
	event.hide('mysticalagriculture:rose_gold_essence')
	event.hide('mysticalagriculture:flight_augment')

// Mob Grinding Utils
	event.hide('mob_grinding_utils:spawner_upgrade_width')
	event.hide('mob_grinding_utils:spawner_upgrade_height')
	event.hide('mob_grinding_utils:entity_conveyor')
	event.hide('mob_grinding_utils:entity_spawner')
	event.hide('mob_grinding_utils:mob_swab')
	event.hide('mob_grinding_utils:mob_swab_used')

// Energetic Sheep
	event.hide('energeticsheep:energetic_shears')

// Apotheosis
	// event.hide('apotheosis:library')

// Waystones
	event.hide('waystones:warp_dust')
	event.hide('waystones:attuned_shard')
	event.hide('waystones:return_scroll')
	event.hide('waystones:bound_scroll')
	event.hide('waystones:warp_scroll')
	event.hide('waystones:warp_plate')
	event.hide('waystones:portstone')

// Extended Crafting
	event.hide('extendedcrafting:pedestal')
	event.hide('extendedcrafting:basic_table')
	event.hide('extendedcrafting:advanced_table')
	event.hide('extendedcrafting:elite_table')
	event.hide('extendedcrafting:ultimate_table')
	event.hide('extendedcrafting:basic_auto_table')
	event.hide('extendedcrafting:elite_auto_table')
	event.hide('extendedcrafting:ultimate_auto_table')
	event.hide('extendedcrafting:handheld_table')

// IMMERSIVE PETROLEUM
	event.hide('immersivepetroleum:bitumen')

// TCON
	event.hide('tconstruct:small_axe_head_sand_cast')
	event.hide('tconstruct:broad_axe_head_red_sand_cast')
	event.hide('tconstruct:wire_sand_cast')
	event.hide('tconstruct:rod_red_sand_cast')
	event.hide('tconstruct:rod_sand_cast')
	event.hide('tconstruct:bow_grip_red_sand_cast')
	event.hide('tconstruct:round_plate_red_sand_cast')
	event.hide('tconstruct:small_axe_head_red_sand_cast')
	event.hide('tconstruct:broad_blade_red_sand_cast')
	event.hide('tconstruct:large_plate_red_sand_cast')
	event.hide('tconstruct:gem_red_sand_cast')
	event.hide('tconstruct:coin_red_sand_cast')
	event.hide('tconstruct:tool_handle_sand_cast')
	event.hide('tconstruct:blank_sand_cast')
	event.hide('tconstruct:repair_kit_red_sand_cast')
	event.hide('tconstruct:tool_binding_sand_cast')
	event.hide('tconstruct:plate_red_sand_cast')
	event.hide('tconstruct:bow_grip_sand_cast')
	event.hide('tconstruct:tough_handle_sand_cast')
	event.hide('tconstruct:hammer_head_sand_cast')
	event.hide('tconstruct:round_plate_sand_cast')
	event.hide('tconstruct:coin_sand_cast')
	event.hide('tconstruct:pick_head_red_sand_cast')
	event.hide('tconstruct:blank_red_sand_cast')
	event.hide('tconstruct:tool_handle_red_sand_cast')
	event.hide('tconstruct:gear_sand_cast')
	event.hide('tconstruct:pick_head_sand_cast')
	event.hide('tconstruct:bow_limb_sand_cast')
	event.hide('tconstruct:bow_limb_red_sand_cast')
	event.hide('tconstruct:repair_kit_sand_cast')
	event.hide('tconstruct:broad_blade_sand_cast')
	event.hide('tconstruct:broad_axe_head_sand_cast')
	event.hide('tconstruct:hammer_head_red_sand_cast')
	event.hide('tconstruct:tool_binding_red_sand_cast')
	event.hide('tconstruct:tough_handle_red_sand_cast')
	event.hide('tconstruct:small_blade_red_sand_cast')
	event.hide('tconstruct:gem_sand_cast')
	event.hide('tconstruct:gear_red_sand_cast')
	event.hide('tconstruct:plate_sand_cast')
	event.hide('tconstruct:large_plate_sand_cast')
	event.hide('tconstruct:wire_red_sand_cast')
	event.hide('tconstruct:small_blade_sand_cast')
	event.hide('tconstruct:small_blade_cast')
	event.hide('tconstruct:gem_cast')
	event.hide('tconstruct:tool_handle_cast')
	event.hide('tconstruct:plate_cast')
	event.hide('tconstruct:repair_kit_cast')
	event.hide('tconstruct:gear_cast')
	event.hide('tconstruct:broad_blade_cast')
	event.hide('tconstruct:wire_cast')
	event.hide('tconstruct:tough_handle_cast')
	event.hide('tconstruct:bow_limb_cast')
	event.hide('tconstruct:round_plate_cast')
	event.hide('tconstruct:rod_cast')
	event.hide('tconstruct:large_plate_cast')
	event.hide('tconstruct:hammer_head_cast')
	event.hide('tconstruct:pick_head_cast')
	event.hide('tconstruct:bow_grip_cast')
	event.hide('tconstruct:coin_cast')
	event.hide('tconstruct:tool_binding_cast')
	event.hide('tconstruct:broad_axe_head_cast')
	event.hide('tconstruct:small_axe_head_cast')
	event.hide('tconstruct:helmet_plating_cast')
	event.hide('tconstruct:chestplate_plating_cast')
	event.hide('tconstruct:leggings_plating_cast')
	event.hide('tconstruct:boots_plating_cast')
	event.hide('tconstruct:maille_cast')
	event.hide('tconstruct:helmet_plating_red_sand_cast')
	event.hide('tconstruct:chestplate_plating_red_sand_cast')
	event.hide('tconstruct:leggings_plating_red_sand_cast')
	event.hide('tconstruct:boots_plating_red_sand_cast')
	event.hide('tconstruct:maille_red_sand_cast')
	event.hide('tconstruct:helmet_plating_sand_cast')
	event.hide('tconstruct:chestplate_plating_sand_cast')
	event.hide('tconstruct:leggings_plating_sand_cast')
	event.hide('tconstruct:boots_plating_sand_cast')
	event.hide('tconstruct:maille_sand_cast')

// Ice & Fire
	event.hide('iceandfire:sapphire_ore')
	event.hide('dragonseeker:dragonseeker')
	event.hide('dragonseeker:epic_dragonseeker')
	event.hide('dragonseeker:legendary_dragonseeker')

// EE
	event.hide('emendatusenigmatica:copper_sword')
	event.hide('emendatusenigmatica:copper_pickaxe')
	event.hide('emendatusenigmatica:copper_shovel')
	event.hide('emendatusenigmatica:copper_hoe')
	event.hide('emendatusenigmatica:copper_helmet')
	event.hide('emendatusenigmatica:copper_chestplate')
	event.hide('emendatusenigmatica:copper_leggings')
	event.hide('emendatusenigmatica:copper_boots')
	event.hide('emendatusenigmatica:sterling_silver_sword')
	event.hide('emendatusenigmatica:sterling_silver_pickaxe')
	event.hide('emendatusenigmatica:sterling_silver_shovel')
	event.hide('emendatusenigmatica:sterling_silver_helmet')
	event.hide('emendatusenigmatica:sterling_silver_chestplate')
	event.hide('emendatusenigmatica:sterling_silver_leggings')
	event.hide('emendatusenigmatica:sterling_silver_boots')

// POWAH
	event.hide('powah:furnator_blazing')
	event.hide('powah:furnator_niotic')
	event.hide('powah:furnator_nitro')
	event.hide('powah:furnator_spirited')
	event.hide('powah:magmator_blazing')
	event.hide('powah:magmator_niotic')
	event.hide('powah:magmator_nitro')
	event.hide('powah:magmator_spirited')
	event.hide('powah:solar_panel_blazing')
	event.hide('powah:solar_panel_niotic')
	event.hide('powah:solar_panel_nitro')
	event.hide('powah:solar_panel_spirited')
	event.hide('powah:thermo_generator_blazing')
	event.hide('powah:thermo_generator_niotic')
	event.hide('powah:thermo_generator_nitro')
	event.hide('powah:thermo_generator_spirited')

// pams
	event.hide('pamhc2foodcore:doughitem')



//
})
//