
#Default difficulty caps at 250
[general]
	#Disable/Enables the whole difficulty scaling of this mod. Requires a mc restart
	"Enable difficulty scaling" = true
	#Time in ticks for which the difficulty shouldnt increase at the beginning. One full minecraft day is 24000 ticks
	#Range: > 0
	"Difficulty Delay" = 0
	#Handles increase in difficulty regarding current difficulty.
	#Format is <minimum current difficulty>-<increase every 2400 ticks>
	#Example ["0-0.01","10-0.1","30-0"]
	#-> So the difficulty increases by 0.01 every 2400 ticks (->0.1 per mc day since a mc day has 24000 ticks) till it reaches a difficulty of 10.
	#Then it increases by 1 per mc day till it reaches 30 and then stops.
	"Difficulty Increase" = ["0-0.01", "10-0", "20-0.05", "30-0", "35-0.05", "50-0", "55-0.05", "80-0", "85-0.05", "100-0", "105-0.05", "200-0", "225-0.05", "250-0"]
	#Wether difficulty should only increase with at least one online players or not
	"Ignore Players" = false
	#If true will increase difficulty by the amount of time skipped. Else will only increase difficulty once.
	"Punish Time Skip" = true
	#Disable/Enable friendly fire for owned pets.
	FriendlyFire = false
	#Blacklist for pet you should't be able to give armor to. Pets from mods, which have custom armor already should be included here (for balancing reasons).
	"Pet Blacklist" = []
	#Treat pet blacklist as whitelist
	"Pet Whitelist" = false
	#Increase difficulty with time
	#Here untill its back as a gamerule
	"Difficulty toggle" = true
	#How the difficulty at a position is calculated. Supported values are: 
	#GLOBAL: Serverwide difficulty value
	#PLAYERMAX: Maximum difficulty of players in a 256 radius around the position
	#PLAYERMEAN: Average difficulty of players in a 256 radius around the position
	#Allowed Values: GLOBAL, PLAYERMAX, PLAYERMEAN
	"Difficulty type" = "PLAYERMEAN"

#Black/Whitelist for various stuff
[list]
	#Entities added here will be blacklisted from their assigned flags. Usage:
	#<entity registry name> or <namespace> followed by any of:
	#[ALL,ATTRIBUTES,ARMOR,HELDITEMS,BLOCKBREAK,USEITEM,LADDER,STEAL,GUARDIAN,PARROT,TARGETVILLAGER,NEUTRALAGGRO,REVERSE].
	#Having no flags is equal to ALL. Use REVERSE to reverse all flags. Some flags do nothing for certain mobs!
	#Examples (without <>):
	#<minecraft:sheep> (equal to minecraft:sheep|ALL) excludes sheeps from all modifications
	#<minecraft:sheep|REVERSE|ATTRIBUTES will> add sheep to attributes modification only
	#<minecraft:sheep|ATTRIBUTES> will add sheep to everything except attributes
	#<minecraft> blacklists all minecraft mobs from everything
	"Entity Configs" = ["ars_nouveau:familiar_whirlisprig", "ad_astra:glacian_ram", "ars_nouveau:wixie", "chococraft:chocobo", "tombstone:grave_guardian", "productivebees:bumble_bee", "occultism:guardian_familiar", "minecraft:glow_squid", "totemic:buffalo", "occultism:dragon_familiar", "minecraft:trader_llama", "totemic:bald_eagle", "ars_nouveau:familiar_wixie", "ars_nouveau:cascading_weald_walker", "ars_nouveau:vexing_weald_walker", "productivebees:creeper_bee", "minecraft:horse", "productivebees:digger_bee", "minecraft:polar_bear", "mutantmonsters:mutant_snow_golem", "productivebees:green_carpenter_bee", "occultism:headless_familiar", "productivebees:dye_bee", "minecraft:llama", "minecraft:pig", "twilightforest:raven", "minecraft:turtle", "minecraft:sheep", "occultism:djinni", "productivebees:cupid_bee", "occultism:mummy_familiar", "minecraft:tadpole", "minecraft:goat", "minecraft:dolphin", "ars_nouveau:animated_block", "farmingforblockheads:merchant", "ars_nouveau:animated_head", "minecraft:cod", "productivebees:neon_cuckoo_bee", "ars_nouveau:familiar_starbuncle", "minecraft:donkey", "ars_nouveau:starbuncle", "twilightforest:loyal_zombie", "minecraft:squid", "minecraft:skeleton_horse", "mutantmonsters:spider_pig", "twilightforest:tiny_bird", "quark:stoneling", "minecraft:cow", "inventorypets:steve_ballmer_entity", "ars_nouveau:dummy", "occultism:marid", "ars_nouveau:familiar_drygmy", "productivebees:lumber_bee", "minecraft:bee", "ars_nouveau:whirlisprig", "the_bumblezone:bee_queen", "quark:shiba", "pneumaticcraft:harvesting_drone", "quark:toretoise", "statues:statue_bat", "ars_nouveau:gift_starby", "deeperdarker:stalker", "minecraft:salmon", "infernalexp:warpbeetle", "productivebees:yellow_black_carpenter_bee", "twilightforest:quest_ram", "minecraft:snow_golem", "energeticsheep:energetic_sheep", "occultism:shub_niggurath_familiar", "minecraft:mooshroom", "ars_nouveau:flourishing_weald_walker", "minecraft:villager", "pneumaticcraft:amadrone", "rottencreatures:treasure_chest", "supplementaries:red_merchant", "rottencreatures:hunter_wolf", "minecraft:rabbit", "minecraft:axolotl", "botania:doppleganger", "pneumaticcraft:drone", "productivebees:mason_bee", "pneumaticcraft:programmable_controller", "occultism:foliot", "productivebees:hoarder_bee", "productivebees:reed_bee", "occultism:greedy_familiar", "infernalexp:glowsilk_moth", "minecraft:strider", "inventorypets:bill_gates_entity", "minecraft:parrot", "quark:crab", "productivebees:rancher_bee", "infernalexp:blackstone_dwarf", "ars_nouveau:drygmy", "twilightforest:bighorn_sheep", "occultism:beholder_familiar", "minecraft:bat", "minecraft:wandering_trader", "pneumaticcraft:logistics_drone", "productivebees:sweat_bee", "ars_nouveau:summon_horse", "occultism:shub_niggurath_spawn", "ars_nouveau:familiar_bookwyrm", "infernalexp:basalt_giant", "productivebees:blue_banded_bee", "ad_astra:lunarian", "minecraft:frog", "minecraft:iron_golem", "mutantmonsters:creeper_minion", "occultism:devil_familiar", "inventorypets:satya_nadella_entity", "twilightforest:deer", "productivebees:nomad_bee", "deeperdarker:shriek_worm", "botania:pixie", "occultism:bat_familiar", "ars_nouveau:familiar_amethyst_golem", "productivebees:ashy_mining_bee", "mythicbotany:alf_pixie", "occultism:blacksmith_familiar", "pneumaticcraft:collector_drone", "infernalexp:glowsquito", "productivebees:collector_bee", "occultism:deer_familiar", "twilightforest:squirrel", "minecraft:mule", "productivebees:chocolate_mining_bee", "unusualend:bolok", "occultism:cthulhu_familiar", "occultism:beaver_familiar", "ars_nouveau:bookwyrm", "minecraft:zombie_horse", "occultism:afrit", "occultism:goat_familiar", "inventorypets:siamese_entity", "ars_nouveau:lily", "occultism:otherworld_bird", "twilightforest:boar", "productivebees:configurable_bee", "minecraft:cat", "minecraft:pufferfish", "ars_nouveau:amethyst_golem", "infernalexp:shroomloin", "ars_nouveau:blazing_weald_walker", "twilightforest:dwarf_rabbit", "deeperdarker:shattered", "minecraft:fox", "ars_nouveau:summon_wolf", "productivebees:farmer_bee", "productivebees:resin_bee", "minecraft:allay", "minecraft:tropical_fish", "pneumaticcraft:guard_drone", "unusualend:ender_firefly", "occultism:chimera_familiar", "mekanism:robit", "ad_astra:lunarian_wandering_trader", "deeperdarker:sculk_snapper", "minecraft:ocelot", "twilightforest:penguin", "the_bumblezone:beehemoth", "productivebees:quarry_bee", "minecraft:chicken", "minecraft:wolf", "occultism:fairy_familiar", "minecraft:panda", "productivebees:leafcutter_bee", "minecraft:ender_dragon", "minecraft:hoglin", "minecraft:illusioner", "minecraft:zombie_horse", "mutantmonsters:mutant_creeper", "mutantmonsters:mutant_enderman", "mutantmonsters:mutant_skeleton", "mutantmonsters:mutant_snow_golem", "mutantmonsters:mutant_zombie", "twilightforest:alpha_yeti", "twilightforest:armored_giant", "twilightforest:death_tome", "twilightforest:fire_beetle", "twilightforest:hedge_spider", "twilightforest:hostile_wolf", "twilightforest:ice_crystal", "twilightforest:king_spider", "twilightforest:knight_phantom", "twilightforest:lich", "twilightforest:minotaur", "twilightforest:mist_wolf", "twilightforest:snow_queen", "twilightforest:ur_ghast", "twilightforest:yeti", "ars_nouveau:wilden_hunter", "ars_nouveau:wilden_stalker", "minecraft:ravager", "minecraft:vindicator", "ars_nouveau:cascading_weald_walker", "ars_nouveau:flourishing_weald_walker", "ars_nouveau:blazing_weald_walker", "ars_nouveau:vexing_weald_walker", "rottencreatures:burned", "rottencreatures:frostbitten", "rottencreatures:mummy", "rottencreatures:dead_beard", "rottencreatures:immortal", "rottencreatures:swampy", "rottencreatures:glacial_hunter", "minecraft:warden", "artifacts:mimic", "alexsmobs:tarantula_hawk", "alexsmobs:raccoon", "alexsmobs:gorilla", "alexsmobs:mantis_shrimp", "alexsmobs:bald_eagle", "alexsmobs:orca", "alexsmobs:cachalot_whale", "alexsmobs:seagull", "alexsmobs:seal", "alexsmobs:hummingbird", "alexsmobs:capuchin_monkey", "alexsmobs:tasmanian_devil", "alexsmobs:guster", "alexsmobs:rattlesnake", "alexsmobs:roadrunner", "alexsmobs:kangaroo", "alexsmobs:elephant", "alexsmobs:crow", "alexsmobs:gazelle", "alexsmobs:crocodile", "alexsmobs:fly", "alexsmobs:sunbird", "alexsmobs:endergrade", "alexsmobs:hammerhead_shark", "alexsmobs:lobster", "alexsmobs:komodo_dragon", "alexsmobs:centipede_body", "alexsmobs:centipede_body", "alexsmobs:centipede_tail", "alexsmobs:warped_toad", "alexsmobs:warped_mosco", "alexsmobs:moose", "alexsmobs:mimicube", "alexsmobs:blobfish", "alexsmobs:cockroach", "alexsmobs:cockroach_egg", "alexsmobs:shoebill", "alexsmobs:soul_vulture", "alexsmobs:snow_leopard", "alexsmobs:spectre", "alexsmobs:alligator_snapping_turtle", "alexsmobs:mungus", "alexsmobs:stradpole", "alexsmobs:straddleboard", "alexsmobs:emu", "alexsmobs:platypus", "alexsmobs:tasmanian_devil", "alexsmobs:kangaroo", "alexsmobs:kangaroo", "alexsmobs:cachalot_whale", "alexsmobs:leafcutter_ant", "alexsmobs:tiger", "alexsmobs:void_worm", "alexsmobs:void_worm_part", "alexsmobs:frilled_shark", "alexsmobs:mimic_octopus", "alexsmobs:grizzly_bear"]
	#Any of the following 
	#[ATTRIBUTES, ARMOR, HELDITEMS, BLOCKBREAK, USEITEM, LADDER, STEAL, GUARDIAN, PARROT, TARGETVILLAGER, NEUTRALAGGRO]
	#added here will disable that feature completely.
	#E.g. ["GUARDIAN"] will disable the guardian feature
	"Flag Blacklist" = []
	#Treat ATTRIBUTES flags as whitelist
	"Attribute Whitelist" = false
	#Treat ARMOR flags as whitelist
	"Armor Equip Whitelist" = false
	#Treat HELDITEMS flags as whitelist
	"Held Equip Whitelist" = false
	#Treat BLOCKBREAK flags as whitelist
	"Breaker Whitelist" = false
	#Treat USEITEM flags as whitelist
	"Item Use Whitelist" = false
	#Treat LADDER flags as whitelist
	"Ladder Whitelist" = false
	#Treat STEAL flags as whitelist
	"Steal Whitelist" = false
	#Treat GUARDIAN flags as whitelist
	"Guardian Whitelist" = false
	#Treat PARROT flags as whitelist
	"Phantom Whitelist" = false
	#Treat TARGETVILLAGER flags as whitelist
	"Villager Whitelist" = false
	#Treat NEUTRALAGGRO flags as whitelist
	"Neutral Aggro Whitelist" = false

#Settings for mod integration
[integration]
	#Should the scaling health mods difficulty system be used instead of this ones. (Requires scaling health mod)
	"Use Scaling Health Mod" = true
	#If true and playerEx is installed will use the level from playerEx as difficulty
	"Use Player EX Mod" = true
	#If true and LevelZ is installed will use the the total skill level from LevelZ as difficulty
	"Use LevelZ Mod" = true

#Settings regarding custom ai for mobs
[ai]
	#Whitelist for blocks, which can be actively broken. 
	#Usage: <registry name;classname;tag;namespace> put "!" infront to exclude blocks
	#Note: If you include common blocks (like grass blocks) the pathfinding can have undesirable results.
	"Block Break Whitelist" = ["forge:glass", "forge:glass_panes", "minecraft:fence_gates", "forge:fence_gates", "minecraft:wooden_doors"]
	#Treat Block Whitelist as Blocklist
	"Breaklist as Blacklist" = false
	#Use the block breaking sound instead of a knocking sound
	Sound = false
	#Chance for a mob to be able to break blocks
	#Range: 0.0 ~ 1.0
	"Breaker Chance" = 0.3
	#Initial cooldown for block breaking mobs
	#Range: > 0
	"Breaker Initial Cooldown" = 120
	#Cooldown for breaking blocks
	#Range: > 0
	"Breaker Cooldown" = 20
	#If mobs should break blocks when not chasing a target
	"Idle Break" = false
	#Chance for a mob to be able to steal items from inventory blocks
	#Range: 0.0 ~ 1.0
	"Stealer Chance" = 0.3
	#Items which will be given to mobs who can break blocks. Empty list = no items. Syntax: id;weight
	#Note: Mobs can only break blocks if the tool they are holding can break the blocks
	"Breaking items" = ["minecraft:diamond_pickaxe;1", "minecraft:iron_axe;2"]
	#Should mobs be able to break block entities? Evaluated before the break list
	"Break BlockEntities" = true
	#Chance for neutral mobs to be aggressive
	#Range: 0.0 ~ 1.0
	"Neutral Aggressive Chance" = 0.1
	#List for of pairs containing which mobs auto target others. Syntax is [mob id]-[mob id] where second value is the target.
	# e.g. minecraft:zombie-minecraft:skeleton makes all zombies target skeletons
	"Auto Target List" = []
	#Difficulty at which mobs are able to break blocks
	#Range: 0.0 ~ 1.7976931348623157E308
	"Difficulty Break AI" = 0.0
	#Difficulty at which mobs are able to steal items
	#Range: 0.0 ~ 1.7976931348623157E308
	"Difficulty Steal AI" = 0.0
	#Chance for mobs to be able to summon an aquatic mount
	#Range: 0.0 ~ 1.0
	"Guardian Chance" = 1.0
	#Chance for mobs to be able to summon a flying mount
	#Range: 0.0 ~ 1.0
	"Phantom Chance" = 0.5

#Configs regarding mobs spawning with equipment
[equipment]
	#Blacklist items from whole mods. Add modid to prevent items from that mod being equipped. (For individual items use the equipment.json)
	"Item Blacklist" = []
	#Use blacklist as whitelist
	"Item Whitelist" = false
	#Blacklist for items mobs should never be able to use.
	#Use as in using the item similar to players (e.g. shooting bows)
	"Item Use Blacklist" = ["bigbrain:buckler"]
	#Turn the use blacklist into a whitelist
	"Item Use Whitelist" = false
	#Blacklist for specific mobs and items they shouldnt use (e.g. skeletons already use bows)
	#<entity registry name-item>
	#For different items but same entity use multiple lines
	#Some special names are BOW, TRIDEN, CROSSBOW refering to every bow/trident/crossbow item (So you dont need to type e.g. every bow item)
	"Entity Item Use Blacklist" = ["minecraft:drowned;TRIDENT", "minecraft:illusioner;BOW", "minecraft:piglin;CROSSBOW", "minecraft:pillager;CROSSBOW", "minecraft:skeleton;BOW", "minecraft:snow_golem;minecraft:snowball", "minecraft:stray;BOW", "minecraft:wither_skeleton;BOW"]
	#Base chance that a mob can have one piece of armor
	#Range: 0.0 ~ 1.0
	"Equipment Chance" = 0.1
	#Base chance for each additional armor pieces
	#Range: 0.0 ~ 1.0
	"Additional Equipment Chance" = 0.3
	#Adds additional x*difficulty% to base equip chance
	#Range: 0.0 ~ 1.7976931348623157E308
	"Equipment Addition" = 0.3
	#Chance for mobs to have a weapon
	#Range: 0.0 ~ 1.0
	"Weapon Chance" = 0.05
	#Adds additional x*difficulty% to base weapon chance
	#Range: 0.0 ~ 1.7976931348623157E308
	"Weapon Chance Add" = 0.3
	#Base chance for each armor pieces to get enchanted
	#Range: 0.0 ~ 1.0
	"Enchanting Chance" = 0.2
	#Adds additional x*difficulty% to base enchanting chance
	#Range: 0.0 ~ 1.7976931348623157E308
	"Enchanting Addition" = 0.2
	#Specify min and max enchanting levels according to difficulty. difficulty-minLevel-maxLevel
	"Enchanting Calc" = ["0-5-10", "25-5-15", "50-10-17", "100-15-25", "200-20-30", "250-30-35"]
	#Chance for mobs to have an item in offhand
	#Range: 0.0 ~ 1.0
	"Item Equip Chance" = 0.05
	#Adds additional x*difficulty% to base item chance
	#Range: 0.0 ~ 1.7976931348623157E308
	"Item Chance add" = 0.2
	#Should mobs drop the armor equipped through this mod? Will not change drops if the mob obtained the armor through other means (e.g. vanilla)
	"Should drop equipment" = false

#Settings for attribute modifiers
[attributes]
	#Health will be multiplied by difficulty*0.016*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Health Increase Multiplier" = 1.0
	#Health will be multiplied by at maximum this. Set to 0 means no limit
	#Range: 0.0 ~ 1.7976931348623157E308
	"Max Health Increase" = 5.0
	#Round health to the nearest x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Round HP" = 0.5
	#Damage will be multiplied by difficulty*0.008*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Damage Increase Multiplier" = 1.0
	#Damage will be multiplied by at maximum this. Set to 0 means no limit
	#Range: 0.0 ~ 1.7976931348623157E308
	"Max Damage Increase" = 3.0
	#Speed will be increased by difficulty*0.0008*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Speed Increase" = 1.0
	#Maximum increase in speed
	#Range: 0.0 ~ 1.0
	"Max Speed" = 0.1
	#Knockback will be increased by difficulty*0.002*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Knockback Increase" = 1.0
	#Maximum increase in knockback
	#Range: 0.0 ~ 1.0
	"Max Knockback" = 0.5
	#Magic resistance will be increased by difficulty*0.0016*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Magic Resistance Increase" = 1.0
	#Maximum increase in magic resistance. Magic reduction is percentage
	#Range: 0.0 ~ 1.0
	"Max Magic Resistance" = 0.4
	#Projectile Damage will be multiplied by 1+difficulty*0.008*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Projectile Damage Increase" = 1.0
	#Projectile damage will be multiplied by maximum of this
	#Range: 0.0 ~ 1.7976931348623157E308
	"Max Projectile Damage" = 2.0

